spring.application.name=aiGym

# H2 Database Setup
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Hibernate settings (update schema automatically)
spring.jpa.hibernate.ddl-auto=update

# Auth0 settings
# Replace with your actual Auth0 Tenant domain (e.g. https://dev-xxxxx.us.auth0.com/)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-bvaiwdm2nmjo3svj.us.auth0.com/
# Replace with your actual Auth0 API Audience (e.g. https://api.aigym.com)
auth0.audience=https://api.aigym.com
